### ISSUE TITLE
Configurate shortcuts

### ISSUE THREAD

**Issue by michaelzoidl** [chabou/hyper-pane#1]
Hi, awesome module, thats exactly what i missed in hyperterm, is it possible to configurate the shortcuts?

If not, how difficult is it to make a fork and install it via the `hpm`? (Would be a solution for me which is okay)

And thanks again for this module :) I can finally move from iterm to hyper \o/

**Comment by chabou** [comment]
@michaelzoidl Thank you for your feedback.

Shortcuts will be configurable very soon.
Which ones do you plan to use ?

**Comment by michaelzoidl** [comment]
I would prefer the same as in iTerm2: `alt+cmd+<arrow-key>`
Also i noticed, how difficult is it to "expane" one pane? I use the shortcuts `shift+command+enter`
Example:
![term-cast](https://cloud.githubusercontent.com/assets/528550/22728015/00a78c32-eddc-11e6-80f0-d5b0dc93a637.gif)

**Comment by chabou** [comment]
I chosen these default shortcuts for two reasons:
* Conforming to current shortcuts for `Select next pane: Ctrl+Alt+Tab`
* Use same shortcut base for arrows key (navigate) and digit keys (jump) but `Alt+Cmd+3`would have taken a screenshot 😆 

But this plugin definitly need a configuration for personal customization.
Stay tuned !

**Comment by chabou** [comment]
Just shipped with 1.0.0 release

**Comment by michaelzoidl** [comment]
Awesome!
