### ISSUE TITLE
Special characters not working on german keyboard

### ISSUE THREAD

**Issue by daviian** [chabou/hyper-pane#10]
Special characters like { [ ² and ³ not working cause of defined shortcut to call pane by number.

Appending configuration to hyper.js and editing shortcut doesn't change anything.

**Comment by chabou** [comment]
Hard to debug this without a german keyboard 😞

**Comment by chabou** [comment]
Please use v2.1.1 canary release of hyper with `hyper-pane@next` as plugin configuration.
It should be fixed. Feel free to comment if not.
