### ISSUE TITLE
Add ability to "rotate" through all panes with a single keyboard shortcut

### ISSUE THREAD

**Issue by ericbiewener** [chabou/hyper-pane#12]
One thing iTerm offers is the ability to rotate forwards and backwards through all panes without needed to choose to navigate "up" or "down" vs "left" or "right." For example, in the following pane layout:

![image](https://user-images.githubusercontent.com/253298/27112079-6a687664-5069-11e7-85fd-b5e3ac3e25da.png)

Pressing the "right" hotkey would go from 1 > 2 > 3 > 4 and then back to 1 when pressed from pane 4. The "down" hotkey would do the same, while "left" or "up" would go in reverse.

I took [a stab at this](https://github.com/ericbiewener/hyper-pane/commit/9f08c7cd5f0c5dd40955a539faac987ec3ab0922) and it appears to be working fine, including with permutation. It introduces a new "rotate" config key that turns it on.

Happy to open a PR if you'd like.

**Comment by chabou** [comment]
Hi @ericbiewener !
Thank you for your feedback.
What you describe: isn't the default behaviour of `Select Next/Prev Pane` in Hyper?
This default shortcut in Hyper will be configurable in next release (currently possible in master).
Or maybe I'm missing the point.

**Comment by ericbiewener** [comment]
You're right! Wasn't aware of that hotkey. Glad to hear it will be configurable in the next release -- the current one is a bit tough!
