### ISSUE TITLE
maximize indicator

### ISSUE THREAD

**Issue by maticrivo** [chabou/hyper-pane#16]
when maximizing a pane, it could be nice to have an indicator showing that its a maximized pane and that there are more panes.
something like iterm does

**Comment by chabou** [comment]
Good idea

iTerm indicator: 
![capture d ecran 2017-08-12 a 12 03 03](https://user-images.githubusercontent.com/4137761/29239768-464aa646-7f56-11e7-88b6-06f707b132d6.png)

**Comment by bravist** [comment]
how to maximize? @maticrivo

**Comment by maticrivo** [comment]
sorry @bravist i don't use hyper much now.. i'm back to using iterm

**Comment by chabou** [comment]
Fix in `2.0.0-rc.5`.
For now, this is just a square.
