### ISSUE TITLE
Moving tabs with Ctrl + Up arrow caused all tabs to disappear

### ISSUE THREAD

**Issue by sanguine8082** [chabou/hyper-pane#18]
I had 4 panes open (2 top, 2 bottom).  I was in the lower right pane, and was able to move left and right.  I went to move up, and then all of the panes disappeared.  The commands are still running (my build script is still opening the programs), but i have nothing but a blank screen.  

I've had several graphical issues with Hyper on this PC for unknown reasons before, so I'm not sure if this is a bug with the add-on, the program itself, or some weird interaction with my PC.  

![image](https://user-images.githubusercontent.com/8801258/28976639-4f21f2c2-7904-11e7-9fa0-74df1428b189.png)

[hyper.js.zip](https://github.com/chabou/hyper-pane/files/1200948/hyper.js.zip)

**Comment by chabou** [comment]
If it happens again, can you check Developer Console?

**Comment by sanguine8082** [comment]
Ok, I will let you know if I catch it happening again

**Comment by chabou** [comment]
I hope that your issue is resolved. Feel free to comment if not.
