### ISSUE TITLE
unimplemented getTermDocument @ bundle.js:5 error on Hyper 2.0.2

### ISSUE THREAD

**Issue by alessio-cpt** [chabou/hyper-pane#19]
Opening a new tab in the newest version of Hyper causes an error. The tab is open and the name is visualized correctly but the keymaps do not work.

**Comment by chabou** [comment]
I have a working `v2` branch. And I made a (merged) PR to have possibility to specify : `hyper-pane@next` in Hyper config.

**Comment by chabou** [comment]
Thank you for your feedback 🙏

**Comment by alessio-cpt** [comment]
It works! Thanks a lot!

**Comment by chabou** [comment]
From v2.1.1 of Hyper, it is possible to specify `@next` in hyper config file.
I just published a `v2.0.0-rc2` on this `@next` update channel.

Please update your plugins.
Thank you again for your feedback
