### ISSUE TITLE
Option to remove panel numbers

### ISSUE THREAD

**Issue by asbjornenge** [chabou/hyper-pane#2]
HI! And thanks for a super great plugin :tada: :rocket: 

I like to keep my terminal super clean, and was wondering about an option to not display the number indicators on the top left corners of each pane. I mostly use the arrow nav, so I'll manage without them :wink:

**Comment by chabou** [comment]
Yes, it will be possible very soon. 
Disabling it and maybe an option to show number indicators only when shortcut base keys (ie. `Ctrl+Alt` by default) are down

**Comment by iamstarkov** [comment]
just heads up: on light themes those numbers are not visible. try this one `hyper-one-light`

**Comment by chabou** [comment]
Light themes are bad and do not deserve this plugin :rofl: 
Ok, I'll try to make font configurable (size, color...)
Thank you for this reminder !

**Comment by iamstarkov** [comment]
can you check pane background color and switch dark/light color based on contrast check result?

**Comment by chabou** [comment]
Difficult to know pane background color. Because terminal himself can change his color (Midnight Commander for example).
Or some nasty plugin can override css like https://github.com/chabou/hyper-autoprofile :rofl:

**Comment by chabou** [comment]
Now you can hide panel numbers or style them by config
