### ISSUE TITLE
Highlighting active pane

### ISSUE THREAD

**Issue by kingmomo** [chabou/hyper-pane#20]
Enhancement request: provide a way to highlight active pane similar to 

> [matheuss/hyper-simple-highlight-active-session](https://github.com/matheuss/hyper-simple-highlight-active-session)

**Comment by chabou** [comment]
Why don't you want this plugin too? Is it incompatible with `hyper-pane` 🤔 ?

**Comment by kingmomo** [comment]
Ahh it was my theme which was messed up.
plugin works just fine.

Thanks for the reply. This issue can be junked.
