### ISSUE TITLE
Switching panes isn't working

### ISSUE THREAD

**Issue by alaughlin** [chabou/hyper-pane#21]
Keyboard shortcuts aren't working. Running Hyper 1.4.8, hyper-pane 2.0.0-rc3, and OSX 10.13.

Should I submit any other info?

**Comment by jgooly** [comment]
Same issue with switching panes using arrows or numbers. However, the focusOnMouseHover is working however. I also tried changing the hotkeys... no luck.

Hyper 1.4.8
hyper-pane 2.0.0-rc3
OSX 10.13.1

**Comment by chabou** [comment]
Oooooops I published v2.0.0-rc3 on `latest` npm channel instead of `next` 😥

**Comment by chabou** [comment]
Should be resolved

**Comment by chabou** [comment]
Sorry for this mistake and thank you for your feedback
