### ISSUE TITLE
macOS unable to maximize

### ISSUE THREAD

**Issue by bravist** [chabou/hyper-pane#23]
Hyper 1.4.8 (stable)

Plugins: 
  hyper-pane (1.3.2),
  hyper-snazzy (1.2.2)

Created by Guillermo Rauch
Copyright © 2017 Zeit, Inc

unable to maximize ?

**Comment by chabou** [comment]
If it is still relevant, please send me your config file.

**Comment by megawubs** [comment]
Hyper 2.0.0 (stable)

Plugins: 
  hyper-snazzy (1.2.2),
  hyperterm-1password (2.0.1),
  hyper-pane (2.0.0)

I just updated to hyper2 and installed this plugin. It is also not possible for me to maximize, not with the default hotkey and not with a different one.

```javascript
paneNavigation: {
    hotkeys: {
      maximize:'ctrl+z'
    }
  }
```

**Comment by megawubs** [comment]
I just restarted hyper2 and it seems to only work with the default hotkey `meta+enter` the configured hotkey does not work.

**Comment by chabou** [comment]
@megawubs it works for me.
Be careful to add `paneNavigation` under `config` key (not at root).

**Comment by chabou** [comment]
I presume that your issue is fixed.
Feel free to add a comment if not.
