### ISSUE TITLE
I hope the indicatorPrefix configuration can support the function

### ISSUE THREAD

**Issue by Dec-F** [chabou/hyper-pane#26]
I hope the indicatorPrefix configuration can support the function, the parameters in the current context, I can easily display the current directory and the like information. 

![image](https://user-images.githubusercontent.com/20250430/40349196-719812f0-5dd8-11e8-97f9-d7c761103a47.png)

Thank you for your contribution

**Comment by chabou** [comment]
This `indicatorPrefix` option should be removed and replaced by a feature that automatically shows shortcut by translating `ctrl` with `^` for example.

I was too lazy to do this.

I think that what you want to achieve should be handled by your shell prompt.
Or you can use another plugin like https://github.com/henrikdahl/hyper-statusline
