### ISSUE TITLE
Plugin error: undefined: Error occurred in `reduceTermGroups`.

### ISSUE THREAD

**Issue by slajax** [chabou/hyper-pane#3]
Thanks for this plugin, really needed this to get hyper up to snuff for my iterm2 replacement however I'm having an issue where it's constantly throwing an error anytime I close a vertical pane.

Please see below:

![screen recording 2017-02-09 at 01 31 pm 1](https://cloud.githubusercontent.com/assets/18702/22804070/4d8ee428-eecc-11e6-950b-b4de72860c7a.gif)

**Comment by chabou** [comment]
Reproduced. Thank you very much for this great feedback 👌

**Comment by chabou** [comment]
Ok this plugin hits a Hyper issue: https://github.com/zeit/hyper/pull/1494

I will publish a protection, pending PR merge and Hyper release

**Comment by slajax** [comment]
@chabou Thanks! Published yet?

**Comment by chabou** [comment]
Just right now
https://github.com/chabou/hyper-pane/releases/tag/0.1.1

**Comment by slajax** [comment]
Trying to verify with `hpm uninstall / install hyper-pane` and seeing same issue.

Where does hyper store installed modules?

**Comment by slajax** [comment]
Nevermind, found it in `~/.hyper_plugins/node_modules/hyper-pane`

Looks like the right version. Still seeing the same issue though.

**Comment by slajax** [comment]
Actually, now the hotkeys do not work at all. I'll check out straight from github and confirm.

**Comment by slajax** [comment]
@chabou confirmed... Rolled back to 5f7818a5e183d0c66b9e570887a4d828ae6bb95f and the hotkeys are working, but still have the error.

**Comment by chabou** [comment]
Thank you. I rolled back npm published version to 0.1.0. It is better to have an error but the hotkeys 😆 
I will finally fix that over the next couple of days

**Comment by chabou** [comment]
Fixed in master and release v0.1.2
But I will test it twice before push it on npm

**Comment by slajax** [comment]
Great! If you want; I can test it from master and confirm before you publish @chabou

**Comment by chabou** [comment]
It would be awesome !

**Comment by slajax** [comment]
@chabou error is gone, so this patch works until the other one lands. Anything we need to change here when it does?

**Comment by chabou** [comment]
Protection will no be useful anymore. But we will keep it for backward compatibility. 
Thank you so much for your validation.
I will publish this release soon.

**Comment by chabou** [comment]
Published on npm ! Thank you @slajax for your support !

**Comment by slajax** [comment]
very welcome @chabou - thanks for the great plugin!

**Comment by freeall** [comment]
@chabou I get this error when I open a new tab and then close it again. I am using version `1.0.0`. Has it regressed somehow?

**Comment by chabou** [comment]
Reproduced !

Previous fix doesn't seem bulletproof 😛 
New issue opened #4, will be fixed very soon

Thank you for your feedback
