### ISSUE TITLE
Open new pane with the same location of the root pane

### ISSUE THREAD

**Issue by OrDuan** [chabou/hyper-pane#30]
HI,
When I'm creating new pane (ctrl+shit+e) the location is always my home directory.
I would except(or at least have a configuration) it to be the same as the root pane I invoked the command from.

Ubuntu 16.04
Hyper 2.0.0
hyper-pane 2.1.3

Thanks!

**Comment by chabou** [comment]
There is another plugin for this purpose: `hypercwd`

**Comment by OrDuan** [comment]
Great, thanks!
