### ISSUE TITLE
Keybinding for resize split terminals

### ISSUE THREAD

**Issue by waldauf** [chabou/hyper-pane#32]
Hello,

can I ask you for adding keybinding for resizing split terminals?

Many thx!

**Comment by chabou** [comment]
You mean to act as a double-click on the pane border?

Can you detail what you expect?

**Comment by chabou** [comment]
I am closing this issue due to its inactivity, but feel free to comment.

**Comment by waldauf** [comment]
I'm sorry I missed notification about your answer. I though keybinding which enable change ratio of split terminal.  
Example: I split horizontal terminal, but want to have bottom one smaller than upper. After split will be ration in size 50:50. With predefined keybinding I will change this ratio.
