### ISSUE TITLE
cmd + alt question

### ISSUE THREAD

**Issue by bannostookaylo** [chabou/hyper-pane#39]
This isn't an issue more of a question, sorry I couldn't find where to just ask a questions.

I would prefer to be able to use `cmd + arrow_key` but I see your warning that says you have to to `cmd + alt` what is this a limitation of that doesn't allow use to just do `cmd + arrow_key` or `ctrl + arrow_key`

**Comment by chabou** [comment]
Hi @bannostookaylo, sorry for the delay.

I am not sure to understand your issue.

>I see your warning that says

What the warning says exactly?


I tried to change my hotkeys to use `cmd + arrow_key` and it works great (on Mac)

**Comment by bannostookaylo** [comment]
Oh you were able to do just `cmd + arrow_key`? On the main page it says 

> ⚠ Warning: Use ctrl+alt or cmd+alt modifier only with arrow and digit key. Otherwise, shortcut will not be detected by Hyper.

Guess I should have just tried it first :P

**Comment by chabou** [comment]
Yes it works.

It is badly explained. I didn't remember exactly why I added this warning. But this more confusing than useful. I'll remove this line.

Thank you for your feedback 🙏
