### ISSUE TITLE
Error using shortcuts -> Panel Creations

### ISSUE THREAD

**Issue by MiguelGalrao** [chabou/hyper-pane#43]
![imagem](https://user-images.githubusercontent.com/31900787/52280949-e9eb1480-2954-11e9-8fe1-c54da35a3725.png)

As seen above when I try to add another panel, Hyper throws that exception.
Shortcut used:
CTRL + SHIFT + D ( or E);

And yes, even without the shortcut this exception still happens.

EDIT:
More detail about the error:

![imagem](https://user-images.githubusercontent.com/31900787/52285687-bad9a080-295e-11e9-956f-43f8b1efcee3.png)

**Comment by chabou** [comment]
It was due to hyperpower. It has been fixed there
