### ISSUE TITLE
Syntax error on reload

### ISSUE THREAD

**Issue by techn0gichida** [chabou/hyper-pane#49]
Hello,

When I add the suggested lines to .hyper.js I get a syntax error on the reload of hyper-pane and all the plugins are missing. Maybe I'm reading something wrong.

Any suggestions?

**Comment by bet4it** [comment]
You need to show us your `.hyper.js`

**Comment by techn0gichida** [comment]
[hyper.js.txt](https://github.com/chabou/hyper-pane/files/3397163/hyper.js.txt)

**Comment by bet4it** [comment]
You lose a comma `,` after `focusOnMouseHover: true`

**Comment by techn0gichida** [comment]
Added the comma but still no plugins and just the default hyper after it reloads. I'm using Fedora latest with the bash shell.

**Comment by bet4it** [comment]
And lose a comma in
```
      inactivePaneOpacity: 0.6 // Set to 1 to disable inactive panes dimming
    } , <-- here
```

**Comment by techn0gichida** [comment]
Thanks for the help. It is working great!

**Comment by chabou** [comment]
Thank you for your help @bet4it 🙏
