### ISSUE TITLE
overwrite default hyper shortcuts

### ISSUE THREAD

**Issue by rodrigomaia17** [chabou/hyper-pane#6]
Hi, thank u for this plugin. I am finally trying to leave tmux because of it. To keep my workflow consistent, I want to use "ctrl+w h' shortcut for navigation-left. But this uses 'ctrl+w' that is used by hyper. Do u think it  can be done?

**Comment by iamstarkov** [comment]
it cant be done yet

**Comment by iamstarkov** [comment]
@rodrigomaia17 make sure to subscribe to this PR https://github.com/zeit/hyper/pull/1509 to get updates

**Comment by rodrigomaia17** [comment]
@iamstarkov thank u! =)
