### ISSUE TITLE
Launch a paned hyper instance

### ISSUE THREAD

**Issue by bpolaszek** [chabou/hyper-pane#60]
Hey there, 

I can't live without that awesome extension, but there's something a little annoying: is there a kind of shell script I could create, that would open a new Hyper instance with pre-defined panes and an init command for each?

Use case is: I regularly need to connect on multiple cloned servers and perform some actions simultaneously on them. I can do that with the broadcast extension, but before, I have to manually enter the ssh address of each host (up to 12) before broadcasting.

Thank you!
Ben

**Comment by bet4it** [comment]
I guess you may be interested in my plugin [hyperinator](https://github.com/bet4it/hyperinator)

**Comment by bpolaszek** [comment]
@bet4it Sounds great indeed, will have a look! Thank you!
