### ISSUE TITLE
[Request] Send commands to all panes

### ISSUE THREAD

**Issue by roginfarrer** [chabou/hyper-pane#8]
This is a big feature that's keeping me from switching from iTerm.

In iTerm, I can hit option+cmd+i to write commands in all panes, which is super handy when working with multiple repos that need to be in sync. I've seen this feature requested on Hyper's github page, but I thought that this feature would be appropriate to the plugin, as well.

**Comment by chabou** [comment]
I think it could be a separated plugin but can you describe what you want exactly: When you hit a hotkey (option+cmd+i), what you type is send to all pane (not tab). And when you hit same hotkey, "mirror mode" is disabled ?

**Comment by roginfarrer** [comment]
Yup, exactly. In iTerm, essentially what happens is that the cursor becomes active in every pane, so that what ever you type gets entered into all panes in that tab.

**Comment by iamstarkov** [comment]
it should be separate plugin

PS. its already can be done by tmux/screen

**Comment by chabou** [comment]
@roginfarrer I made this plugin: https://www.npmjs.com/package/hyper-broadcast

Can you try it and give me some feedbacks ?
I had to change shortcuts to `b` and not `i` because, you know: `option+cmd+i` opens dev-tools 😝
